language:
  - java
  - groovy
  - r

jdk:
  - oraclejdk8

before_install:
  - alias Rscript='R CMD BATCH'

install:
  - mvn clean install -Dmaven.javadoc.skip=true -q
  - java -jar target/vdjtools-*.jar RInstall