language:
  - java
  - groovy
  - r

sudo: required

jdk: oraclejdk8

install:
  - Rscript -e "print('test')"
  - mvn clean install -Dmaven.javadoc.skip=true -q
  - java -jar target/vdjtools-*.jar RInstall